version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
    command: /bin/bash -c "python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    networks:
      - repairmybike-network

networks:
  repairmybike-network:
    driver: bridge